### ISSUE TITLE
I got block from google

### ISSUE THREAD

**Issue by njob45** [adnane-X-tebbaa/Katana#2]
I am getting an error given below(any suggestion):
.
Traceback (most recent call last):
  File "katana-ds.py", line 66, in <module>
    from Modes import Gmode
  File "/root/tools/Katana/Modes/Gmode.py", line 69, in <module>
    for gamma in search(query, tld=beta, num=7,pause=2): 
  File "/usr/local/lib/python3.7/dist-packages/googlesearch/__init__.py", line 312, in search
    html = get_page(url, user_agent)
  File "/usr/local/lib/python3.7/dist-packages/googlesearch/__init__.py", line 176, in get_page
    response = urlopen(request)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

**Comment by adnane-X-tebbaa** [comment]
Hi njob45 just try  to change the used TLD  (see TLDs.txt for more  TLDs) or check your connectivity
changing the TLD might work 
thank you

**Comment by njob45** [comment]
Hi adnane-X-tebbaa
Yes it did solved the problem. Thank you so much
